title: 개발일기
email: jjoyj0401@gmail.com
description: ""
author: ""
baseurl: ""
url: "https://youngddo.github.io"

# Language and Timezone
lang: ko
timezone: Asia/Seoul

# Social Profiles
twitter_username:   
github_username: youngddo
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-B54X2XZZGN # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
